Change: Do not use deprecated ruff CLI
greenbone/actions pull request #1119
Opened 2024-05-13 07:58 UTC by jwulfheide-gb

## What
Using ruff 0.4.3, we get the following warning 

> warning: ruff <path> is deprecated. Use ruff check <path> instead.

when using the `lint-python` action with `linter` set to `ruff`.

I have not tested this locally. If that is expected, could you point my to some piece of information on how to do it?

## Why

The behavior of `ruff .` may change in future versions.

2024-05-21 07:37 UTC, bjoernricks requested changes
Hi,

could you try to just run `linter: ruff check` in your workflow? I am quite sure this PR is unnecessary.

2024-05-22 07:59 UTC, jwulfheide-gb commented
> Hi,
> 
> could you try to just run `linter: ruff check` in your workflow? I am quite sure this PR is unnecessary.

yeah, absolutely we could.

we also discussed that approach. [the docs](https://github.com/greenbone/actions/blob/main/lint-python/README.md?plain=1#L34) seem to suggest that the usage that was intended originally was `linter: ruff`. that is why we thought it would be nicer to fix it here. that way the user of the action would not be responsible for specific CLI syntax.

but obviously we can also change it on our site.

2024-05-22 08:11 UTC, bjoernricks commented
The intention was to only allow to specify the linter executable/script to be run. Because we don't know which linter or executable will pop up in the future we should leave it as it is then.

2024-05-22 08:11 UTC, closed without merging

2024-05-22 08:11 UTC, bjoernricks commented
Thanks for your PR nevertheless :-)