Add: mypy-linting-action for python
greenbone/actions pull request #145
Opened 2022-10-11 12:50 UTC by Tacire

**What**:

**Why**:

To introduce mypy into greenbone python repositories

**How**:

Copied and modified the linting-python action and adjust it to run mypy

**Checklist**:

- [ ] Tests
- [ ] CHANGELOG.md entry
- [ ] Documentation

2022-10-11 12:52 UTC, y0urself requested changes

2022-10-11 12:52 UTC, y0urself commented on mypy-python/action.yaml
> +    description: "Python packages to lint"
```suggestion
    description: "Python packages to check with mypy"
```

2022-10-11 12:53 UTC, y0urself requested changes

2022-10-11 12:53 UTC, y0urself commented on mypy-python/action.yaml
> +description: "An action to lint Greenbone Python packages"
```suggestion
description: "An action that verifies python type hints by using mypy"
```

2022-10-11 15:11 UTC, bjoernricks commented on mypy-python/action.yaml
> +      uses: greenbone/actions/poetry@v1
Must be main in main branch and v2 in v2 branch.
```suggestion
      uses: greenbone/actions/poetry@main
```

2022-10-17 08:23 UTC, bjoernricks approved these changes

2022-10-24 09:00 UTC, y0urself approved these changes

2022-10-24 09:00 UTC, merged