Add: Container Signing action
greenbone/actions pull request #635
Opened 2023-05-23 03:35 UTC by pascalholthaus

## What
Add: Container Signing action

## Why
DEVOPS-574

## References
DEVOPS-574

2023-05-23 06:07 UTC, bjoernricks requested changes

2023-05-23 06:07 UTC, bjoernricks commented on container-signing/action.yaml
> +          xargs -I {} cosign sign --recursive --key env://COSIGN_KEY {}@${{ inputs.docker-digest }}
```suggestion
        echo "${{ inputs.image-tags }}" | \
          xargs -I {} cosign sign --recursive --key env://COSIGN_KEY {}@${{ inputs.image-digest }}
```

2023-05-23 06:07 UTC, bjoernricks commented on container-signing/action.yaml
> +    description: "Set the cosign key password, it not set a keyless signature will be created."
```suggestion
    description: "Set the cosign key password, if not set a keyless signature will be created."
```

2023-05-23 06:07 UTC, bjoernricks commented on container-signing/action.yaml
> +    description: "Set the cosign key, it not set a keyless signature will be created."
```suggestion
    description: "Set the cosign key, if not set a keyless signature will be created."
```

2023-05-23 06:07 UTC, bjoernricks commented on container-signing/README.md
> +Cosign based action to create container signatures.
```suggestion
Cosign based action to create container signatures. Depending on the input public/private key or keyless signatures are created.
```

2023-05-23 06:07 UTC, bjoernricks commented on container-signing/action.yaml
> +    - uses: sigstore/cosign-installer@main
IMHo we should use the latest release version.
```suggestion
    - uses: sigstore/cosign-installer@v3
```

2023-05-23 06:07 UTC, bjoernricks commented on container-signing/action.yaml
> +         xargs -I {} cosign sign --recursive {}@${{ inputs.docker-digest }}
```suggestion
       echo "${{ inputs.image-tags }}" | \
         xargs -I {} cosign sign --recursive {}@${{ inputs.image-digest }}
```

2023-05-23 06:32 UTC, pascalholthaus commented on container-signing/README.md
> +Cosign based action to create container signatures.
done

2023-05-23 06:36 UTC, bjoernricks commented on container-signing/README.md
> +|cosign-key|Set the cosign key, if not set a keyless signature will be created.|true|
```suggestion
|Input Variable|Description| |
|--------------|-----------|--------|
|image-tags|Set the tags from the docker meta action e.g the output of steps.meta.outputs.tags.|Required|
|image-digest|Set the digest from the docker build and push action e.g the output of steps.build-and-push.outputs.digest.|Optional|
|cosign-key-password|Set the cosign key password, if not set a keyless signature will be created.|Optional|
|cosign-key|Set the cosign key, if not set a keyless signature will be created.|Optional|
```

2023-05-23 06:44 UTC, bjoernricks approved these changes

2023-05-23 07:34 UTC, bjoernricks approved these changes

2023-05-23 08:58 UTC, bjoernricks submitted a review, later dismissed

2023-05-24 06:56 UTC, y0urself approved these changes

2023-05-24 07:10 UTC, merged